### PR TITLE
Novel

### PR DESCRIPTION
**Pull request by Permoment-95**
Added match modality train and validate scripts.

### CODE REVIEW

**Comment by rcannood** [comment]
Hey Gleb! 

Thanks for your PR! I appreciate the time and effort you took to submit your code to this repository.

I have a few comments I'd like to see fixed before merging this PR.

* When running the `test.sh` script, I obtain the following scores:
  `[{"method_id":"novel","ADT2GEX":0.0209,"ATAC2GEX":0.0481,"GEX2ADT":0.0209,"GEX2ATAC":0.0481,"Overall":0.0345}]`
  This is quite similar to [submission 169594](https://evalai.s3.amazonaws.com/media/submission_files/submission_169594/f1ea2ebd-6bad-48c7-98d5-dffc6455cee4.zip), which obtained the following scores:
 `[{"method_id":"first_try_submit","ADT2GEX":0.0225,"ATAC2GEX":0.0482,"GEX2ADT":0.0225,"GEX2ATAC":0.0482,"Overall":0.0353}]`
  However, [submission 170690](https://evalai.s3.amazonaws.com/media/submission_files/submission_170690/605605da-933c-4ca6-9153-63389774bd15.zip) got better scores on ADT2GEX and GEX2ADT:
  `[{"method_id":"first_try_submit","ADT2GEX":0.0373,"ATAC2GEX":0.0412,"GEX2ADT":0.0373,"GEX2ATAC":0.0412,"Overall":0.0392}]`.
  Could you edit this PR such that it contains the best models of both submissions? That is, for ADT2GEX and GEX2ADT it uses the code of submission 170690; for ATAC2GEX and GEX2ATAC it uses the code of submission 169594.

* Please create a README.md which describes your method.
* Please fill in the metadata in the config.vsh.yaml: the description, some urls (optional), your github usernames (optional), your ORCID ids (optional).

Let me know when the first issue is resolved so I can rerun the analysis.

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Hey Gleb!

I'm running into the following issue:

```bash
$ export PIPELINE_REPO="openproblems-bio/neurips2021_multimodal_viash"
$ export NXF_VER=21.04.1
$ export PIPELINE_VERSION=1.4.0
$ method_id=novel
$ task_id=match_modality
$ 
$ 
$ # CITE ADT2GEX
$ dataset_id=openproblems_bmmc_cite_phase2_mod2
$ dataset_id_val=openproblems_bmmc_cite_phase2_mod2
$ dataset_path=output/datasets/$task_id/$dataset_id/$dataset_id.censor_dataset
$ dataset_path_val=output/datasets/$task_id/$dataset_id_val/$dataset_id_val.censor_dataset
$ pretrain_path=output/pretrain/$task_id/$method_id/$dataset_id.${method_id}_train.output_pretrain/
$ pred_path=output/predictions/$task_id/$dataset_id/$dataset_id
$ 
$ target/docker/${task_id}_methods/${method_id}_train/${method_id}_train \
>   --input_train_mod1 ${dataset_path}.output_train_mod1.h5ad \
>   --input_train_mod2 ${dataset_path}.output_train_mod2.h5ad \
>   --input_train_sol ${dataset_path}.output_train_sol.h5ad \
>   --input_test_mod1 ${dataset_path}.output_test_mod1.h5ad \
>   --input_test_mod2 ${dataset_path}.output_test_mod2.h5ad \
>   --input_test_sol ${dataset_path}.output_test_sol.h5ad \
>   --output_pretrain ${pretrain_path}
```

```
1/7000 * Epoch (train):  97%|█████████▋| 30/31 [00:01<00:00, 21.09it/s, T=31.889, loss=1.761, lr=7.800e-05, momentum=0.900]Start train
Traceback (most recent call last):
  File "/viash_automount/home/ec2-user/ssd/tmp//viash-run-novel_train-CiCD80", line 137, in <module>
    verbose=True
  File "/opt/conda/lib/python3.7/site-packages/catalyst/runners/runner.py", line 542, in train
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 854, in run
    self._run_event("on_exception")
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 788, in _run_event
    getattr(self, event)(self)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 780, in on_exception
    raise self.exception
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 850, in run
    self._run_experiment()
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 840, in _run_experiment
    self.engine.spawn(self._run_stage)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/engine.py", line 138, in spawn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 831, in _run_stage
    self._run_epoch()
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 824, in _run_epoch
    self._run_loader()
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 819, in _run_loader
    self._run_event("on_loader_end")
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 786, in _run_event
    getattr(callback, event)(self)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/callbacks/metric.py", line 322, in on_loader_end
    metrics = self.metric.compute_key_value()
  File "/viash_automount/home/ec2-user/ssd/neurips2021_multimodal_topmethods/target/docker/match_modality_methods/novel_train/catalyst_tools.py", line 77, in compute_key_value
    logits = all_embeddings_first@all_embeddings_second.T
RuntimeError: CUDA out of memory. Tried to allocate 14.07 GiB (GPU 0; 14.76 GiB total capacity; 91.64 MiB already allocated; 13.69 GiB free; 130.00 MiB reserved in total by PyTorch)
```

Is there a way we can reduce the memory consumption by just a _tiny_ bit?

**Comment by Permoment-95** [comment]
Hey, Robrecht!

I'll send a new PR in 10 minutes. I managed to create the metrics you asked
for. Now readme will make beautiful and make PR!

чт, 27 янв. 2022 г. в 17:31, Robrecht Cannoodt ***@***.***>:

**Comment by rcannood** [comment]
Thanks Gleb, good job! I reran everything and got the following score:

```json
[{"method_id":"novel","ADT2GEX":0.0427,"ATAC2GEX":0.0468,"GEX2ADT":0.0427,"GEX2ATAC":0.0468,"Overall":0.0448}]
```

I'll go ahead and merge this PR :)

**Pull request merged**
