### PR TITLE
Team AXX methods of predict modality task

### PR DESCRIPTION
**Pull request by xuerchen**
Please expect minor revisions of readme in our methods folder. Thank you!

### CODE REVIEW

**Comment by xuerchen** [comment]
Here are our github id:
Xueer Chen https://github.com/xuerchen
Jiwei Liu https://github.com/daxiongshu

Thank you!

**Review by rcannood — COMMENTED** [review]
Source code looks OK! I'm currently running the test.sh to validate.

**Comment by rcannood** [comment]
The script finished successfully and the same scores were obtained as in the competition!
```
N E X T F L O W  ~  version 21.04.1
Pulling openproblems-bio/neurips2021_multimodal_viash ...
Launching `openproblems-bio/neurips2021_multimodal_viash` [loving_jennings] - revision: a28e0c22c5 [1.4.0]
executor >  local (17)
[d4/5d95b6] process > get_id_predictions (4)                                                          [100%] 4 of 4 ✔
[94/ffca9e] process > get_id_solutions (2)                                                            [100%] 4 of 4, cached: 4 ✔
[b3/92d144] process > bind_tsv_rows:bind_tsv_rows_process (meta_metric)                               [100%] 1 of 1, cached: 1 ✔
[25/5cb893] process > mse:mse_process (openproblems_bmmc_cite_phase2_PM_gex2adt)                      [100%] 4 of 4 ✔
[6c/b5cd30] process > correlation:correlation_process (openproblems_bmmc_multiome_phase2_PM_atac2gex) [100%] 4 of 4 ✔
[f4/4e81e2] process > check_format:check_format_process (openproblems_bmmc_cite_phase2_PM_gex2adt)    [100%] 4 of 4 ✔
[71/c8bf79] process > final_scores:final_scores_process (output)                                      [100%] 1 of 1 ✔
Completed at: 10-Jan-2022 09:21:19
Duration    : 1m 11s
CPU hours   : 0.1 (3.1% cached)
Succeeded   : 17
Cached      : 5

[{"method_id":"simple_mlp","ADT2GEX":0.3263,"ATAC2GEX":0.2375,"GEX2ADT":0.398,"GEX2ATAC":0.1795,"Overall":0.2853}]
```

Thanks for adding simple_mlp to the repo!

**Comment by xuerchen** [comment]
Thank you so much for editing and merging the PR! Could you please add our method link to the table in the [Readme.md](https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/blob/main/README.md)?
image

**Comment by rcannood** [comment]
No, thank you for sending me this PR in the first place! 

I'll fix the table straight away. Which name would you like to give to your method? "SimpleMLP"? "AXX"?

**Pull request merged**
